[package]
name = "storage-wizard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jwalk = "0.8.1"
sha2 = { version = "0.10.6", features = ["asm"] }
